language: go

go:
  - 1.8.x
  - 1.9.x

services:
  - rabbitmq

env:
  - AMQP_USERNAME=guest AMQP_PASSWORD=guest AMQP_DEFAULT_PORT=5672

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -v github.com/golang/lint/golint
  - dep ensure

script: go test -v -cover -tags integration ./exchange ./indices ./connector ./slice
